create table app_releases (
    id bigint generated by default as identity,
    platform varchar(20) not null,
    version_code bigint not null,
    version_name varchar(100) not null,
    file_name varchar(255) not null,
    file_size bigint not null,
    sha256 varchar(64) not null,
    git_revision varchar(40) not null,
    jenkins_build bigint not null,
    published_at timestamp with time zone not null,
    constraint pk_app_releases primary key (id),
    constraint uk_app_releases_platform_version unique (platform, version_code),
    constraint uk_app_releases_file_name unique (file_name),
    constraint ck_app_releases_platform check (platform in ('ANDROID')),
    constraint ck_app_releases_version_code check (version_code > 0),
    constraint ck_app_releases_file_size check (file_size > 0),
    constraint ck_app_releases_sha256 check (char_length(sha256) = 64),
    constraint ck_app_releases_jenkins_build check (jenkins_build > 0)
);

create index idx_app_releases_platform_latest
    on app_releases (platform, version_code);
