create table character_operation_jobs (
    id bigint generated by default as identity,
    account_id bigint not null,
    operation_type varchar(30) not null,
    status varchar(20) not null,
    source_character_id bigint,
    target_character_id bigint not null,
    request_payload text,
    progress_payload text not null default '[]',
    completed_step_ids text not null default '[]',
    result_payload text,
    message text,
    started_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    finished_at timestamp with time zone,
    constraint pk_character_operation_jobs primary key (id),
    constraint fk_character_operation_jobs_account
        foreign key (account_id) references hof_accounts(id) on delete cascade,
    constraint fk_character_operation_jobs_source
        foreign key (source_character_id) references characters(id) on delete set null,
    constraint fk_character_operation_jobs_target
        foreign key (target_character_id) references characters(id) on delete cascade,
    constraint ck_character_operation_jobs_type
        check (operation_type in ('DEEP_SYNC', 'TRANSFER')),
    constraint ck_character_operation_jobs_status
        check (status in ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'STOPPED'))
);

create index idx_character_operation_jobs_account_started
    on character_operation_jobs(account_id, started_at desc, id desc);
