CREATE TABLE character_recovery_originals (
    job_id BIGINT CONSTRAINT pk_character_recovery_originals PRIMARY KEY
        CONSTRAINT fk_character_recovery_originals_job REFERENCES character_operation_jobs(id) ON DELETE CASCADE,
    hof_character_id VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    guard_value VARCHAR(255) NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    collection_complete BOOLEAN NOT NULL DEFAULT FALSE,
    collection_error TEXT,
    restore_attempts INTEGER NOT NULL DEFAULT 0 CONSTRAINT ck_character_recovery_originals_attempts CHECK (restore_attempts >= 0),
    observed_equipment VARCHAR(64),
    observed_patterns VARCHAR(64),
    observed_conditions VARCHAR(64),
    observed_position VARCHAR(255),
    observed_guard VARCHAR(255),
    pending_change VARCHAR(32) CONSTRAINT ck_character_recovery_originals_pending CHECK (pending_change IN (
        'LOAD_PATTERN', 'LOAD_EQUIPMENT', 'RESTORE_EQUIPMENT', 'RESTORE_PATTERN', 'RESTORE_POSITION'
    )),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE character_recovery_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_character_recovery_patterns PRIMARY KEY,
    job_id BIGINT NOT NULL CONSTRAINT fk_character_recovery_patterns_job REFERENCES character_recovery_originals(job_id) ON DELETE CASCADE,
    row_index INTEGER NOT NULL,
    judge_value VARCHAR(255) NOT NULL,
    quantity VARCHAR(255) NOT NULL,
    skill VARCHAR(255) NOT NULL,
    CONSTRAINT uk_character_recovery_patterns_job_row UNIQUE (job_id, row_index)
);

CREATE TABLE character_recovery_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_character_recovery_equipment PRIMARY KEY,
    job_id BIGINT NOT NULL CONSTRAINT fk_character_recovery_equipment_job REFERENCES character_recovery_originals(job_id) ON DELETE CASCADE,
    item_order INTEGER NOT NULL,
    slot VARCHAR(255) NOT NULL,
    part VARCHAR(255) NOT NULL,
    name TEXT NOT NULL,
    icon_url TEXT NOT NULL,
    description TEXT NOT NULL,
    CONSTRAINT uk_character_recovery_equipment_job_order UNIQUE (job_id, item_order)
);
