alter table automation_convergence_shadow_evaluations
    add column successful_observation_count integer;
alter table automation_convergence_shadow_evaluations
    add column first_pending_at timestamp(6) with time zone;
alter table automation_convergence_shadow_evaluations
    add column submitted_at timestamp(6) with time zone;
alter table automation_convergence_shadow_evaluations
    add column next_probe_at timestamp(6) with time zone;
alter table automation_convergence_shadow_evaluations
    add column finished_at timestamp(6) with time zone;
alter table automation_convergence_shadow_evaluations
    add column checkpoint_updated_at timestamp(6) with time zone;
alter table automation_convergence_shadow_evaluations
    add column selection_entry_id bigint;
alter table automation_convergence_shadow_evaluations
    add column baseline_fingerprint_hash varchar(64);
alter table automation_convergence_shadow_evaluations
    add column observation_only boolean;
alter table automation_convergence_shadow_evaluations
    add column recorded_sequence bigint generated by default as identity;

create index idx_automation_convergence_shadow_restore
    on automation_convergence_shadow_evaluations(account_id, execution_identity_hash, recorded_sequence desc);
